name: oauth1
version: 2.0.0
description: '"RFC 5849: The OAuth 1.0 Protocol" client implementation for Dart.'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  crypto: ^3.0.3
  http: ^1.1.0

dev_dependencies:
  test: ^1.16.5
